import path from 'path';
import fs from 'fs';
import { defineConfig } from '@playwright/test';

const projectRoot = process.cwd();
const host = process.env.E2E_HOST ?? process.env.HOST ?? '127.0.0.1';
const port = Number(process.env.E2E_PORT ?? process.env.PORT ?? '5001');
const baseURL = process.env.PLAYWRIGHT_BASE_URL ?? `http://${host}:${port}`;
const defaultPython = process.platform === 'win32'
  ? path.join(projectRoot, 'venv', 'Scripts', 'python.exe')
  : path.join(projectRoot, 'venv', 'bin', 'python');
const pythonInterpreter = process.env.PLAYWRIGHT_PYTHON ?? defaultPython;
const runLocalScript = process.env.PLAYWRIGHT_APP_ENTRY ?? path.join(projectRoot, 'run_local.py');
const webServerCommand = `EUTRACKER_BYPASS_LOGIN=1 HOST=127.0.0.1 PORT=5001 python3 ${JSON.stringify(runLocalScript).slice(1, -1)}`;
const defaultDbPath = process.env.PLAYWRIGHT_DB_PATH ?? path.join(projectRoot, 'tests', 'tmp', 'playwright_e2e.db');

try {
  fs.mkdirSync(path.dirname(defaultDbPath), { recursive: true });
  if (fs.existsSync(defaultDbPath)) {
    fs.unlinkSync(defaultDbPath);
  }
} catch {
  // best effort cleanup; failures will surface during tests if the DB cannot be initialised
}

// Check if login state file exists
const statePath = path.join(projectRoot, 'tests', 'auth', 'state.json');
const storageState = statePath; // enforced; generated by globalSetup if missing

export default defineConfig({
  globalSetup: path.join(projectRoot, 'tests', 'global.setup.ts'),
  testDir: 'tests',
  testMatch: ['**/*.spec.{js,ts}'],
  timeout: 30_000,
  expect: {
    timeout: 5_000,
  },
  retries: process.env.CI ? 1 : 0,
  reporter: [
    ['list'],
    ['html', { outputFolder: 'reports/playwright_phase1', open: 'never' }],
    ['json', { outputFile: 'reports/phase1_test_report.json' }],
  ],
  use: {
    baseURL,
    headless: !!process.env.CI,
    browserName: 'chromium',
    viewport: { width: 1440, height: 900 },
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    storageState,
  },
  webServer: [
    {
      command: "EUTRACKER_BYPASS_LOGIN=1 HOST=127.0.0.1 PORT=5001 python3 run_local.py",
      url: "http://127.0.0.1:5001/healthz",
      reuseExistingServer: true,
      timeout: 120_000,
    },
  ],
});
